include(
    ":app",
    ":core:common",
    ":core:mvi",
    ":core:mvi-android",
    ":core:navigation",
    ":core:uikit",
    ":data",
    ":domain",
    // features
    ":features:course",
    ":features:coursefinish",
    ":features:courses",
    ":features:onboarding",
    ":features:settings",
    ":features:signin",
    ":features:signup",
    ":features:timemanagement"
)